# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 1478dd4
_src_path: https://github.com/vivienm/copier-python-uv
author_email: v.maisonneuve@gmail.com
author_name: Vivien Maisonneuve
build_system: maturin
copyright_holder: Vivien Maisonneuve
copyright_year: 2022
github_account: vivienm
github_pages: true
hosting_platform: github
license: MIT
package_name: uniq-ch
project_description: A Python library for counting distinct elements in a stream,
    using ClickHouse uniq data structure.
project_name: uniq-ch
project_type: library
python_version: '3.10'
repo_name: python-uniq-ch
